version: 2.1

jobs:
  build_and_test:

    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      - run: 
          name: Install Python, Flask and other Dependencies
          # echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
          command: |
            pip install -r requirements.txt


      - run:
          name: Testing
          command: |
            pytest --junitxml=teset-reports/junit.xml --html=test-reports/pytest-report.html --self-contained-html

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - build_and_test  



# OLD ENV

      # - run:
      #     name: Starting up MySQL
      #     command: |
      #       for i in `seq 1 10`;
      #       do
      #         nc -z 127.0.0.1 3306 && echo Success && exit 0
      #         echo -n .
      #         sleep 1
      #       done
      #       echo Failed waiting for MySQL && exit 1

      # - run:
      #     name: Install MySQL CLI, Dependencies and Run Script
      #     command: |
      #       sudo apt-get install default-mysql-client
      #       mysql -u root -h localhost -rootpw --execute="DROP DATABASE IF EXISTS `g3t4`"
      #       mysql -u root -h localhost -rootpw --execute="CREATE DATABASE `g3t4`"
      #       mysql -u root -h localhost -rootpw g3t4 < dbloadscript.sql