version: 2.1

jobs:
  build_and_test:

    docker:
      - image: circleci/python:3.8
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: g3t4
          MYSQL_USER: root
          MYSQL_PASSWORD: ''

    steps:
      - checkout

      - run: 
          name: Install Python, Flask and other Dependencies
          # echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
          command: |
            pip install -r requirements.txt

      - run:
          name: Starting up MySQL
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

      - run:
          name: Install MySQL CLI, Dependencies and Run Script
          command: |
            sudo apt-get install default-mysql-client
            mysql -h 127.0.0.1 -u user -P g3t4 < dbloadscript.sql

      - run:
          name: Testing
          command: |
            pytest --junitxml=teset-reports/junit.xml --html=test-reports/pytest-report.html --self-contained-html

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
  build_test:
    jobs:
      - build_and_test  